**Imagine having full system of neural network, 3 inputs layer, 2 hidden layers with 4 neuron each and three output**

**1. Coding one neuron**


Here we zoom into hidden layer such that:
*   Select a single neuron which automatically have 1 bias (like constant)
*   selected neuron has 3 inputs neuron with three weights correspond to each input
* This will provide only one output



In [1]:
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

print(output)

35.7


Let's select different neuron in hidden layer such that we add one input neuron on top of the ones we already have

In [2]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

print(output)

4.8


**2. Coding 3 neurons with 4 inputs**



*   Inputs remains the same (i.e. 4)
*   since we have 3 neuron to code we need 3 different weights and biases, with 1 weight and bias for each output neuron
* **N.B.:** To get the best prediction or outputs you need to change the weights and biases



In [3]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [ inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
           inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]

print(output)

[4.8, 1.21, 2.385]


**3. Coding neuron with loops**

**i.** Use arrays and list to simplify the code

In [4]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = []
for nueron_weights, nueron_bias in zip(weights, biases):
  neuron_output = 0
  for n_input, weight in zip(inputs, nueron_weights):
      neuron_output += n_input*weight
  neuron_output += nueron_bias
  layer_outputs.append(neuron_output)
  
print(layer_outputs)

[4.8, 1.21, 2.385]


**ii. Use dot product to code one Neuron**

In [5]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = np.dot(weights, inputs) + bias
print(output)

4.8


**iii. Now let's code 3 neurons using similar approach**

In [6]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


**4. Batches, a 1 layer**

This means Separate datasets (inputs) into parts that will be trained in iterrations (separately)

In [7]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


**4. Add another layer**

To add another layer we need to add another set of weights correspond to that layer's neurons

In [8]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

weights2 = [[0.1, -0.14, 0.5], 
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases = [2, 3, 0.5]
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


**5. Introducing OBJECT**

Here to be able to change the size of the hidden layer's neurons we introduce the object for simplification

In [15]:
np.random.seed(0)
X = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]     #Sample data

#Define the two hidden layers

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
layer2.forward(layer1.output)

print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
